export const LOGIN ='LOGIN';
export const REGISTRATION ='REGISTRATION';
export const LOGIN_ERROR='LOGIN_ERROR';
export const REGISTRATION_ERROR='REGISTRATION_ERROR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const REGISTRATION_SUCCESS='REGISTRATION_SUCCESS';
export const RESET_PASSWORD='RESET_PASSWORD';
export const FORGOT_PASSWORD='FORGOT_PASSWORD';
export const VERIFY_ACCOUNT='VERIFY_ACCOUNT';
export const VERIFICATION_CODE='VERIFICATION_CODE';
export const EMPTY_USER_ERRORS='EMPTY_USER_ERRORS';
export const EMPTY_USER_SUCCESS = 'EMPTY_USER_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const GET_TOKEN_WITH_REFRESH_TOKEN = 'GET_TOKEN_WITH_REFRESH_TOKEN';
export const TAKE_TOKEN='TAKE_TOKEN';
export const REFRESH_TOKEN_ERROR='REFRESH_TOKEN_ERROR';


