export const CREATE_GROUP='CREATE_GROUP';
export const DELETE_GROUP='DELETE_GROUP';
export const ERROR='ERROR_GROUP';
export const SUCCESS='SUCCESS';
export const FETCH_GROUPS='FETCH_GROUPS';
export const GET_GROUP_POSTS='GET_GROUP_POSTS';
