export const CREATE_GROUP='CREATE_GROUP';
export const DELETE_GROUP='DELETE_GROUP';
export const ERROR='ERROR_GROUP';
export const SUCCESS='SUCCESS';
export const FETCH_GROUPS='FETCH_GROUPS';
export const FETCH_GROUPS_BY_ID='FETCH_GROUPS_BY_ID';
